using System.Collections.Generic;

namespace Wake.Narrative
{
    public static class SceneContextBarkCatalog
    {
        private static readonly AmbientBarkRecord[] Entries =
        {
            B("SCENE_P01_PORT", "DOCK_PORTER",
                "머서 씨 짐에는 기자 장비 표식이 붙어 있습니다. 초대장 확인 전에는 선적하지 않겠습니다.",
                "professional", "P-01", "PORT"),
            B("SCENE_P02_GANGWAY", "CREW_SECURITY",
                "명단의 붉은 수정 표시는 비서실 승인 건입니다. 수정 시각은 15시 31분으로 남아 있습니다.",
                "firm", "P-02", "GANGWAY"),
            B("SCENE_P03_SUITE", "SUITE_STEWARD",
                "협박장이 도착한 뒤 회장님은 오래된 오르페우스 호 사진을 치우지 말라고 하셨습니다.",
                "uneasy", "P-03", "RICHARD_SUITE"),
            B("SCENE_D101_ATRIUM", "ATRIUM_GUIDE",
                "소개 행사는 17시에 시작합니다. 보안, 의무, 기관 책임자는 중앙 원형 바닥 주변에 대기 중입니다.",
                "professional", "D1-01", "ATRIUM"),
            B("SCENE_D102_DINING", "DINING_SOMMELIER",
                "머서 씨와 클레어 씨의 언성이 높아졌지만 이블린 씨는 자리를 뜨지 않고 대화를 지켜봤습니다.",
                "observant", "D1-02", "DINING"),
            B("SCENE_D103_BALLROOM", "BALLROOM_MUSICIAN",
                "21시 무렵엔 모두 무대 쪽을 봤습니다. 기자분만 곡이 끝나기 전에 서비스 문으로 향했어요.",
                "recalling", "D1-03", "BALLROOM"),
            B("SCENE_D104_STAIRS", "CREW_ATTENDANT",
                "21시 22분, 제가 다니엘 머서 씨를 마지막으로 봤습니다. 승객 출입 금지 표지 앞에서 단말을 확인한 뒤 아래층으로 내려갔어요.",
                "uneasy", "D1-04", "SERVICE7"),
            B("SCENE_D105_BALLROOM", "CREW_ATTENDANT",
                "이블린 씨가 회장님께 단말을 보여드린 시각은 22시 35분입니다. 두 분 모두 볼룸에 있었습니다.",
                "professional", "D1-05", "BALLROOM"),
            B("SCENE_D106_HORIZON", "CREW_ATTENDANT",
                "예약 종료 뒤 이 문으로 들어간 승객은 없습니다. 세면대 점검 알림만 22시 27분에 잡혔습니다.",
                "shaken", "D1-06", "HORIZON"),
            B("SCENE_D107_MEDBAY", "SHIP_MEDIC",
                "시신 이송 시각과 검체 봉인 번호를 따로 기록했습니다. 공식 발표와 검시 기록은 분리 보관하겠습니다.",
                "clinical", "D1-07", "MEDBAY"),
            B("SCENE_D201_HORIZON", "CREW_SECURITY",
                "외벽 발판은 밤새 잠금 상태였습니다. 젖은 흔적도, 안전줄 사용 기록도 없습니다.",
                "firm", "D2-01", "HORIZON"),
            B("SCENE_D202_HORIZON", "CREW_ATTENDANT",
                "카펫의 젖은 중심이 시신 아래와 어긋나 있었습니다. 발견 때부터 그랬습니다.",
                "uneasy", "D2-02", "HORIZON"),
            B("SCENE_D203_MEDBAY", "SHIP_MEDIC",
                "안정제는 처방량 안이었지만 저온과 함께라면 체온 기반 사망 시각 추정이 흔들릴 수 있습니다.",
                "clinical", "D2-03", "MEDBAY"),
            B("SCENE_D204_SECURITY", "SECURITY_OPERATOR",
                "22시 18분 화재감지기 신호가 정확히 4초 비었습니다. 출입문 로그에는 같은 시각 변화가 없습니다.",
                "focused", "D2-04", "SECURITY"),
            B("SCENE_D205_HORIZON", "CREW_ENGINEER",
                "장식 패널 위 검은 섬유는 객실 자재가 아닙니다. 화물 운반백 안감과 비슷합니다.",
                "matter_of_fact", "D2-05", "HORIZON"),
            B("SCENE_D206_NEWS", "PASSENGER_D",
                "다니엘은 예약 기사 원본을 단말과 객실 저장소에 나눠 뒀습니다. 한쪽이 없어져도 발행되게요.",
                "concerned", "D2-06", "CABIN_DANIEL"),
            B("SCENE_D301_NEWS", "PASSENGER_D",
                "기사는 8시에 자동 공개됐습니다. 다니엘이 직접 누른 게 아니라 전날 설정한 예약 발행입니다.",
                "reporting", "D3-01", "NEWS_LOUNGE"),
            B("SCENE_D302_SUITE", "SUITE_STEWARD",
                "회장님은 그날 밤 스위트에 돌아온 뒤 아들 사진 앞에서 한참 서 있었습니다.",
                "quiet", "D3-02", "RICHARD_SUITE"),
            B("SCENE_D303_ENGINE", "CHIEF_ENGINEER",
                "선장님은 원본 항해 모듈이 금고에 남아 있다는 말을 기관 교대기록 확인 뒤에 꺼냈습니다.",
                "grave", "D3-03", "BRIDGE"),
            B("SCENE_D304_VAULT", "VAULT_GUARD",
                "21시 05분 접근은 이중 인증이었습니다. 마커스의 보안 키와 이블린의 임원 키가 함께 찍혔습니다.",
                "firm", "D3-04", "VAULT"),
            B("SCENE_D305_PROMENADE", "PASSENGER_D",
                "‘사실은 비용을 요구한다’는 표현, VIP 브리핑에서 이블린 씨가 쓰는 걸 들은 적 있습니다.",
                "thoughtful", "D3-05", "PROMENADE"),
            B("SCENE_D401_SECURITY", "SECURITY_OPERATOR",
                "마커스 책임자는 오늘 아침 자기 인증 기록 사본을 먼저 요청했습니다. 평소 절차와 달랐습니다.",
                "uneasy", "D4-01", "SECURITY"),
            B("SCENE_D402_STAIRS", "CREW_SECURITY",
                "추락 직전 아래쪽 계단을 통과한 사람은 없습니다. 난간 쪽 비상등만 한 번 깜박였습니다.",
                "firm", "D4-02", "CREW_STAIRS"),
            B("SCENE_D403_STAIRS", "CREW_ENGINEER",
                "물자국은 청소 배관 밸브에서 시작합니다. 발자국은 한 사람 몫이고 방향도 아래쪽뿐입니다.",
                "focused", "D4-03", "CREW_STAIRS"),
            B("SCENE_D404_MEDBAY", "SHIP_MEDIC",
                "마커스는 말은 못 하지만 눈 깜박임과 손가락으로 답할 수 있습니다. 질문은 다섯 개로 제한해 주세요.",
                "clinical", "D4-04", "MEDBAY"),
            B("SCENE_D501_VIP", "VIP_HOST",
                "클레어 씨 객실에는 사람 대신 서비스 로봇이 들어갔습니다. 커튼 자동화도 같은 시각에 작동했습니다.",
                "shaken", "D5-01", "CABIN_CLAIRE"),
            B("SCENE_D502_VIP", "ROBOTICS_TECH",
                "로봇 적재함에 드라이아이스 가루가 남았습니다. 연막 장치는 원격 호출과 함께 실을 수 있습니다.",
                "focused", "D5-02", "CABIN_CLAIRE"),
            B("SCENE_D503_SECURITY", "SECURITY_OPERATOR",
                "클레어 씨는 태블릿 위치를 먼저 밝히는 조건으로 진술 기록의 공개 범위를 협상하고 있습니다.",
                "professional", "D5-03", "INTERVIEW"),
            B("SCENE_D504_HORIZON", "CREW_ATTENDANT",
                "세면대는 수동 사용이 아니라 정비 타이머로 켜졌습니다. 방 안에 사람이 없어도 작동합니다.",
                "realization", "D5-04", "HORIZON"),
            B("SCENE_D601_ENGINE", "CHIEF_ENGINEER",
                "22시 17분의 86킬로그램 보정은 파도와 반대 방향입니다. 선체가 아니라 내부 하중이 움직였습니다.",
                "focused", "D6-01", "ENGINE_CONTROL"),
            B("SCENE_D602_RAIL", "RAIL_TECHNICIAN",
                "이 분기 스위치는 밸러스트 별실에서 호라이즌 룸 천장까지 직결됩니다. 중간 하역 지점은 없습니다.",
                "matter_of_fact", "D6-02", "SERVICE_RAIL"),
            B("SCENE_D603_BALLAST", "BALLAST_CONTROLLER",
                "질소 퍼지는 보통 두 명이 확인합니다. 그날 기록은 임원 권한 하나로 절차가 건너뛰어졌습니다.",
                "uneasy", "D6-03", "BALLAST_CONTROL_ANNEX"),
            B("SCENE_D604_MEDBAY", "SHIP_MEDIC",
                "보호면 파편의 수지와 다니엘 손톱 아래 조각이 같습니다. 살아 있을 때 가까이서 긁은 흔적입니다.",
                "firm", "D6-04", "MEDBAY"),
            B("SCENE_D605_NEWS", "PASSENGER_D",
                "다니엘의 예약 발행 시각은 바꿀 수 있어도 원본 서버 타임스탬프는 남습니다. 사건 순서의 기준으로 쓰세요.",
                "helpful", "D6-05", "NEWS_LOUNGE"),
            B("SCENE_D701_VAULT", "VAULT_GUARD",
                "화재경보가 울렸지만 금고 안 센서는 연기와 열을 감지하지 않았습니다. 경보만 원격으로 들어왔습니다.",
                "urgent", "D7-01", "VAULT"),
            B("SCENE_D702_MEDBAY", "SHIP_MEDIC",
                "보호면 바깥이 아니라 안쪽에서 이블린의 주 시료가 나왔습니다. 착용자를 가리키는 위치입니다.",
                "clinical", "D7-02", "MEDBAY"),
            B("SCENE_D703_ARCHIVE", "ARCHIVIST",
                "백업 모듈은 삭제되지 않고 덮어쓰기 됐습니다. 남은 음성 조각을 시간순으로 겹치면 원문이 복구됩니다.",
                "focused", "D7-03", "ARCHIVE"),
            B("SCENE_D704_PROMENADE", "CREW_ATTENDANT",
                "이블린 씨가 이 구간의 승무원을 모두 물린 뒤 탐정님을 기다렸습니다. 사적인 대화를 원한 듯합니다.",
                "uneasy", "D7-04", "PROMENADE"),
            B("SCENE_D801_HORIZON", "CREW_SECURITY",
                "호출 대상 전원의 신원과 소지품을 확인했습니다. 최종 심문이 끝날 때까지 출입문을 통제합니다.",
                "commanding", "D8-01", "HORIZON"),
            B("SCENE_D802_DECK", "CREW_SECURITY",
                "선미 갑판은 비웠고 난간 접근로도 막았습니다. 마커스 책임자가 체포 절차를 준비 중입니다.",
                "firm", "D8-02", "OPEN_DECK"),
            B("SCENE_D803_PORT", "DOCK_PORTER",
                "생존자와 증거 화물은 분리 하선합니다. 이블린 쇼는 보안 통로로 인계될 예정입니다.",
                "professional", "D8-03", "PORT")
        };

        public static IReadOnlyList<AmbientBarkRecord> All => Entries;

        private static AmbientBarkRecord B(
            string id,
            string speaker,
            string text,
            string emotion,
            string sceneId,
            string location) =>
            new(id, speaker, text, emotion, $"scene={sceneId}", location);
    }
}
